name: publish

env:
  DB_PROFILE: ${{ secrets.DB_PROFILE }}

on:
  workflow_dispatch:
    inputs:
      db_profile:
        type: string
        description: 'Databricks environment to publish HTML from'
        default: DEMO
      db_path:
        type: string
        description: 'Repository path on databricks environment'
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/databricks-industry-solutions/industry-solutions-release

      - name: Package solution accelerator
        run: |
          
          import os
          import json
          from databricks.solution import Accelerator
          
          environments = json.loads(os.environ['DB_PROFILES'])
          if '${{ github.event.repository.db_profile }}' not in environments:
            raise Exception('Profile is not supported. Please check secret information')
          
          environment = environments['${{ github.event.repository.db_profile }}']

          Accelerator(
            db_host=environment['host'],
            db_token=environment['token'],
            db_path='${{ github.event.inputs.path }}',
            db_name='${{ github.event.repository.name }}',
          ).release()

        shell: python

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4