name: publish

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo ${GITHUB_ACTOR}
          echo ${{ secrets.GITHUB_TOKEN }}
